Dvora
jamberusimantov/tech_career-employers pull request #12
Opened 2021-05-25 17:50 UTC by DvoraSchwartz

2021-05-26 12:15 UTC, jamberusimantov reviewed
ctrl c ctrl v

2021-05-26 12:19 UTC, orgolestani reviewed
Finish form component

2021-05-27 12:25 UTC, yonatanpa requested changes

2021-05-27 12:25 UTC, yonatanpa commented on client/src/components/Form.ts
> +        <React.Fragment>
Refactor <React.Fragment> => <></>

2021-05-27 12:25 UTC, yonatanpa commented on client/src/components/Layout/Header.tsx
> +
Remove empty line

2021-05-30 09:17 UTC, closed without merging

2021-05-30 09:17 UTC, DvoraSchwartz commented
Updated